package by.itacademy.newsportal.controller;

public enum CommandName {
	
	GO_TO_AUTHORIZATION_PAGE, GO_TO_REGISTRATION_PAGE, REGISTRATION_NEW_USER, UNKNOWN_COMMAND, GO_TO_MAIN_PAGE, SIGNIN, CHANGE_LOCALE,
	LOGOUT, GO_TO_PROFILE_USER_PAGE, ADDNEWS, GO_TO_ADMIN_PAGE, GO_TO_ADDNEWS_PAGE, GO_TO_CATEGORY_PAGE, GO_TO_ONE_NEWS_PAGE,
    GET_DISAPPROVED_NEWS, APPROVED_OF_NEWS, GET_USER_NEWS, GO_TO_UPDATE_NEWS_PAGE, UPDATE_NEWS, ALL_NEWS, DELETE_NEWS, GET_DELETED_NEWS
}
