package by.itacademy.newsportal.controller;

public enum CommandName {
	
	GO_TO_AUTHORIZATION_PAGE, GO_TO_REGISTRATION_PAGE, REGISTRATION_NEW_USER, UNKNOWN_COMMAND, GO_TO_MAIN_PAGE, SIGNIN, CHANGE_LOCALE,
	LOGOUT, GO_TO_PROFILE_USER_PAGE, ADDNEWS, GO_TO_ADMIN_PAGE

}
